### ISSUE TITLE
Record select with conditions bug on rails 4.2.3

### ISSUE THREAD

**Issue by JoaoFelipe** [scambra/recordselect#12]
I'm using rails 4.2.3 with active_scaffold 3.4.23 and recordselect 3.4.6

On my controller, I used
```ruby
config.columns[:course].form_ui = :record_select
config.columns[:course].options[:params] = {available: true}
```

When I click on the record select, it throws the exception:
```
Started GET "/courses/browse?available=true&search=" for 127.0.0.1 at 2015-07-28 21:58:21 -0300
Processing by CoursesController#browse as */*
  Parameters: {"available"=>"true", "search"=>""}
  User Load (0.2ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = ?  ORDER BY "users"."id" ASC LIMIT 1  [["id", 1]]
Completed 500 Internal Server Error in 16ms (ActiveRecord: 0.2ms)

NoMethodError - undefined method `type_cast' for #<ActiveRecord::ConnectionAdapters::Column:0x007f5a649b25b0>:
  recordselect (3.4.6) lib/record_select/conditions.rb:82:in `record_select_condition_for_column'
  recordselect (3.4.6) lib/record_select/conditions.rb:67:in `block in record_select_conditions_from_params'
  actionpack (4.2.3) lib/action_controller/metal/strong_parameters.rb:185:in `each_pair'
  recordselect (3.4.6) lib/record_select/conditions.rb:63:in `record_select_conditions_from_params'
  recordselect (3.4.6) lib/record_select/conditions.rb:14:in `record_select_conditions'
  recordselect (3.4.6) lib/record_select/actions.rb:6:in `browse'
  actionpack (4.2.3) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
...
```

I think that the method type_cast in line https://github.com/scambra/recordselect/blob/master/lib/record_select/conditions.rb#L82 should be type_cast_from_user on rails 4.2

**Comment by scambra** [comment]
let me know if it works, as I'm not using rails 4.2 right now, and I will release new version

**Comment by JoaoFelipe** [comment]
The git version works, but the rubygems (3.4.7) doesn't. 
I think you submited the wrong version there.

**Comment by scambra** [comment]
I didn't release yet, I was waiting someone using 4.2 confirms to be working, 3.4.7 was released before this fix. I will release 3.4.8 now, thanks
